init:
  - git config --global core.autocrlf true
version: '{build}'
environment:  
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  access_token:
    secure: gPLaCoISbGAJCbPE7vGAEkRMtiDH17XvyEzweZlp8pt6zjsOCTMZlmd1296tzgcz
  git_email:
    secure: dCEJcIf4jXWH0PrQcRaXuvvT8l7C5GwosxOsmi0c564=
# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
# Install scripts. (runs after repo cloning)
install:  
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install gitbook-cli -g
  - gitbook install
build_script:
  - make
test: off
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "codeyu"
  - git config --global core.autocrlf true
  - git checkout master
  - git subtree split --prefix _book -b gh-pages
  - git push -f origin gh-pages:gh-pages